# **Instalation des bibliothèque**

In [1]:
!pip install pydub
!pip install librosa

# **Converter les fichiers .ogg en des fichiers .wav**

In [2]:
import os
from pydub import AudioSegment

def convert_folder_ogg_to_wav(input_folder, output_folder):
    # Create the output directory if it doesn't exist
    os.makedirs(output_folder, exist_ok=True)

    # Parcourir tous les dossiers dans le répertoire principal
    for folder_name in os.listdir(input_folder):
        folder_path = os.path.join(input_folder, folder_name)
        
        # Ignorer les fichiers non-dossiers
        if not os.path.isdir(folder_path):
            continue
        
        # Parcourir tous les fichiers dans le dossier
        for filename in os.listdir(folder_path):
            file_path = os.path.join(folder_path, filename)
            
            # Ignorer les fichiers qui ne sont pas au format OGG
            if not filename.lower().endswith(".ogg"):
                continue
            
            # Charger le fichier audio OGG
            sound = AudioSegment.from_ogg(file_path)
            
            # Créer le chemin de sortie pour le fichier WAV
            wav_filename = os.path.splitext(filename)[0] + ".wav"
            output_path = os.path.join(output_folder, folder_name, wav_filename)
            
            # Créer le dossier de sortie s'il n'existe pas
            os.makedirs(os.path.dirname(output_path), exist_ok=True)
            
            # Exporter le fichier audio en format WAV
            sound.export(output_path, format="wav")
            print(f"Conversion terminée. Fichier enregistré sous : {output_path}")

# Les chemins d'accès de dataset "Data (ESC-10)"
input_folder_data_ESC10 = "/kaggle/input/tp-02-audio/Data (ESC-10)/Data (ESC-10)"
output_folder_data_ESC10 = "/kaggle/working/Data (ESC-10) (en wav)"

# Appeler la fonction de conversion de dataset "Data (ESC-10)"
convert_folder_ogg_to_wav(input_folder_data_ESC10, output_folder_data_ESC10)

# Les chemins d'accès de dataset "Data"
input_folder_data = "/kaggle/input/tp-02-audio/Data/Data"
output_folder_data = "/kaggle/working/Data (en wav)"

# Appeler la fonction de conversion de dataset "Data"
convert_folder_ogg_to_wav(input_folder_data, output_folder_data)

Conversion terminée. Fichier enregistré sous : /kaggle/working/Data (ESC-10) (en wav)/006 - Person sneeze/4-167642-A.wav
Conversion terminée. Fichier enregistré sous : /kaggle/working/Data (ESC-10) (en wav)/006 - Person sneeze/1-59324-A.wav
Conversion terminée. Fichier enregistré sous : /kaggle/working/Data (ESC-10) (en wav)/006 - Person sneeze/2-130978-A.wav
Conversion terminée. Fichier enregistré sous : /kaggle/working/Data (ESC-10) (en wav)/006 - Person sneeze/3-144692-A.wav
Conversion terminée. Fichier enregistré sous : /kaggle/working/Data (ESC-10) (en wav)/006 - Person sneeze/1-47273-A.wav
Conversion terminée. Fichier enregistré sous : /kaggle/working/Data (ESC-10) (en wav)/006 - Person sneeze/5-194533-A.wav
Conversion terminée. Fichier enregistré sous : /kaggle/working/Data (ESC-10) (en wav)/006 - Person sneeze/2-119102-A.wav
Conversion terminée. Fichier enregistré sous : /kaggle/working/Data (ESC-10) (en wav)/006 - Person sneeze/5-220027-A.wav
Conversion terminée. Fichier enreg

# **Partition les données en Train et Test**

In [3]:
import os
import shutil
from sklearn.model_selection import train_test_split

def partition_train_test(output_folder):
    # Créer les dossiers Train et Test dans le dossier Data (en wav)
    train_folder = os.path.join(output_folder, "Train")
    test_folder = os.path.join(output_folder, "Test")
    os.makedirs(train_folder, exist_ok=True)
    os.makedirs(test_folder, exist_ok=True)

    # Récupérer la liste des dossiers dans le dossier Data (en wav)
    audio_folders = [f for f in os.listdir(output_folder) if os.path.isdir(os.path.join(output_folder, f))]

    # Vérifier s'il y a des dossiers audio à diviser
    if len(audio_folders) == 0:
        print("Aucun dossier audio trouvé dans le répertoire spécifié.")
    else:
        for folder in audio_folders:
            # Récupérer la liste des fichiers WAV dans le dossier
            wav_files = [f for f in os.listdir(os.path.join(output_folder, folder)) if f.lower().endswith(".wav")]

            # Vérifier si la liste des fichiers n'est pas vide
            if len(wav_files) > 0:
                # Diviser la liste des fichiers en ensembles d'entraînement et de test
                train_files, test_files = train_test_split(wav_files, test_size=0.2, random_state=42)

                # Créer les dossiers Train et Test pour chaque dossier
                train_folder_path = os.path.join(train_folder, folder)
                test_folder_path = os.path.join(test_folder, folder)
                os.makedirs(train_folder_path, exist_ok=True)
                os.makedirs(test_folder_path, exist_ok=True)

                # Déplacer les fichiers d'entraînement vers le dossier Train
                for file in train_files:
                    src_path = os.path.join(output_folder, folder, file)
                    dest_path = os.path.join(train_folder_path, file)
                    shutil.move(src_path, dest_path)

                # Déplacer les fichiers de test vers le dossier Test
                for file in test_files:
                    src_path = os.path.join(output_folder, folder, file)
                    dest_path = os.path.join(test_folder_path, file)
                    shutil.move(src_path, dest_path)

                # Supprimer le dossier d'origine
                shutil.rmtree(os.path.join(output_folder, folder))

                print(f"Partitionnement des fichiers pour {folder} terminé.")
            else:
                print(f"Aucun fichier WAV trouvé dans le dossier {folder}. Aucune action effectuée.")

# Appeler la fonction de partition pour dataset "Data"
partition_train_test(output_folder_data)

# Appeler la fonction de partition pour dataset "Data ESC-10"
partition_train_test(output_folder_data_ESC10)

Partitionnement des fichiers pour 105 - Frog terminé.
Aucun fichier WAV trouvé dans le dossier Test. Aucune action effectuée.
Partitionnement des fichiers pour 103 - Pig terminé.
Partitionnement des fichiers pour 101 - Dog terminé.
Aucun fichier WAV trouvé dans le dossier Train. Aucune action effectuée.
Partitionnement des fichiers pour 102 - Rooster terminé.
Partitionnement des fichiers pour 104 - Cow terminé.
Partitionnement des fichiers pour 001 - Dog bark terminé.
Partitionnement des fichiers pour 009 - Rooster terminé.
Partitionnement des fichiers pour 007 - Helicopter terminé.
Aucun fichier WAV trouvé dans le dossier Test. Aucune action effectuée.
Partitionnement des fichiers pour 002 - Rain terminé.
Partitionnement des fichiers pour 006 - Person sneeze terminé.
Partitionnement des fichiers pour 010 - Fire crackling terminé.
Aucun fichier WAV trouvé dans le dossier Train. Aucune action effectuée.
Partitionnement des fichiers pour 004 - Baby cry terminé.
Partitionnement des fichie

# **Extraction des Caractéristiques Audio**

In [4]:
import librosa
import numpy as np

#lecture des données audios ainsi que l'éxtraction des caractérestiques
def extract_feature(file_path):
    audio, sample_rate = librosa.load(file_path, dtype="float32")
    mfccs = np.mean(librosa.feature.mfcc(y=audio, sr=sample_rate, n_mfcc=40).T, axis=0)
    chroma = np.mean(librosa.feature.chroma_stft(y=audio, sr=sample_rate).T, axis=0)
    mel = np.mean(librosa.feature.melspectrogram(y=audio, sr=sample_rate).T, axis=0)
    contrast = np.mean(librosa.feature.spectral_contrast(S=librosa.stft(audio), sr=sample_rate).T, axis=0)
    tonnetz = np.mean(librosa.feature.tonnetz(y=librosa.effects.harmonic(audio), sr=sample_rate).T, axis=0)

    return np.concatenate([mfccs, chroma, mel, contrast, tonnetz]) # il returne un vecteur concaténés des 4 descripteur( features) au totale 193 éléments
    #return mfccs,chroma,mel,contrast,tonnetz
    #return mfccs # prend uniquement les 40 Mfccs (un vecteur de 40 éléments)
    #return mfccs,chroma # rend uniquement les 40 Mfccs et 12 chroma (un vecteur de 40 +12 =52 éléments)
    #return mfccs,chroma,mel # rend uniquement les 40 Mfccs et 12 chroma et 128 mels (un vecteur de 40 +12+128 =52+128=180 éléments

# **Analyse des fichiers audio**

In [5]:
import os
def parse_audio_files(folder_path):
    features = []
    labels = []

    for label in os.listdir(folder_path):
        label_path = os.path.join(folder_path, label)

        if not os.path.isdir(label_path):
            continue

        for filename in os.listdir(label_path):
            file_path = os.path.join(label_path, filename)
            feature_vector = extract_feature(file_path)

            features.append(feature_vector)
            labels.append(label)

    return np.array(features), np.array(labels)

train_folder_path_data_ESC10 = "./Data (ESC-10) (en wav)/Train"
train_features_data_ESC10, train_labels_data_ESC10 = parse_audio_files(train_folder_path_data_ESC10)

test_folder_path_data_ESC10 = "./Data (ESC-10) (en wav)/Test"
test_features_data_ESC10, test_labels_data_ESC10 = parse_audio_files(test_folder_path_data_ESC10)

train_folder_path_data = "./Data (en wav)/Train"
train_features_data, train_labels_data = parse_audio_files(train_folder_path_data)

test_folder_path_data = "./Data (en wav)/Test"
test_features_data, test_labels_data = parse_audio_files(test_folder_path_data)

/opt/conda/lib/python3.10/site-packages/librosa/feature/spectral.py:520: ComplexWarning: Casting complex values to real discards the imaginary part
  valley[..., k, :] = np.mean(sortedr[..., :idx, :], axis=-2)
/opt/conda/lib/python3.10/site-packages/librosa/feature/spectral.py:521: ComplexWarning: Casting complex values to real discards the imaginary part
  peak[..., k, :] = np.mean(sortedr[..., -idx:, :], axis=-2)
/opt/conda/lib/python3.10/site-packages/librosa/feature/spectral.py:520: ComplexWarning: Casting complex values to real discards the imaginary part
  valley[..., k, :] = np.mean(sortedr[..., :idx, :], axis=-2)
/opt/conda/lib/python3.10/site-packages/librosa/feature/spectral.py:521: ComplexWarning: Casting complex values to real discards the imaginary part
  peak[..., k, :] = np.mean(sortedr[..., -idx:, :], axis=-2)
/opt/conda/lib/python3.10/site-packages/librosa/feature/spectral.py:520: ComplexWarning: Casting complex values to real discards the imaginary part
  valley[..., 

# **Division des données en un dossier d’entraînement et un dossier de test**

**Pour dataset "Data ESC-10" :**

In [6]:
import os
import numpy as np

# Définir le chemin du dossier Numpy
numpy_folder = "Numpy Data ESC-10"

# Vérifier si le dossier existe, sinon le créer
if not os.path.exists(numpy_folder):
    os.makedirs(numpy_folder)

# Chemins pour les fichiers d'apprentissage
feat_train_path = os.path.join(numpy_folder, "feat_train_data_ESC10.npy")
label_train_path = os.path.join(numpy_folder, "label_train_data_ESC10.npy")

# Chemins pour les fichiers de test
feat_test_path = os.path.join(numpy_folder, "feat_test_data_ESC10.npy")
label_test_path = os.path.join(numpy_folder, "label_test_data_ESC10.npy")

# Sauvegarder les fichiers d'apprentissage
np.save(feat_train_path, train_features_data_ESC10)
np.save(label_train_path, train_labels_data_ESC10)

# Sauvegarder les fichiers de test
np.save(feat_test_path, test_features_data_ESC10)
np.save(label_test_path, test_labels_data_ESC10)


# Importe les donneés apprentissage et test via la fonction load
# Load data from numpy file for train
X_train_data_ESC10 =  np.load("./Numpy Data ESC-10/feat_train_data_ESC10.npy")
y_train_data_ESC10 =  np.load("./Numpy Data ESC-10/label_train_data_ESC10.npy").ravel()

# Load data from numpy file for test
X_test_data_ESC10 =  np.load("./Numpy Data ESC-10/feat_test_data_ESC10.npy")
y_test_data_ESC10 =  np.load("./Numpy Data ESC-10/label_test_data_ESC10.npy").ravel()

# afficher les dimmonsion des vecteurs
print(X_train_data_ESC10.shape) # données d'apprentissage
print(X_test_data_ESC10.shape)# donneés de test

(320, 193)
(80, 193)


**Pour dataset "Data" :**

In [7]:
import os
import numpy as np

# Définir le chemin du dossier Numpy
numpy_folder = "Numpy Data"

# Vérifier si le dossier existe, sinon le créer
if not os.path.exists(numpy_folder):
    os.makedirs(numpy_folder)

# Chemins pour les fichiers d'apprentissage
feat_train_path = os.path.join(numpy_folder, "feat_train_data.npy")
label_train_path = os.path.join(numpy_folder, "label_train_data.npy")

# Chemins pour les fichiers de test
feat_test_path = os.path.join(numpy_folder, "feat_test_data.npy")
label_test_path = os.path.join(numpy_folder, "label_test_data.npy")

# Sauvegarder les fichiers d'apprentissage
np.save(feat_train_path, train_features_data)
np.save(label_train_path, train_labels_data)

# Sauvegarder les fichiers de test
np.save(feat_test_path, test_features_data)
np.save(label_test_path, test_labels_data)

# Load data from numpy file for train
X_train_data =  np.load("./Numpy Data/feat_train_data.npy")
y_train_data =  np.load("./Numpy Data/label_train_data.npy").ravel()

# Load data from numpy file for test
X_test_data =  np.load("./Numpy Data/feat_test_data.npy")
y_test_data =  np.load("./Numpy Data/label_test_data.npy").ravel()

# afficher les dimmonsion des vecteurs
print(X_train_data.shape) # données d'apprentissage
print(X_test_data.shape)# donneés de test

(160, 193)
(40, 193)


# **Création et Entraînement du Modèle**

# Avec RNN (Résaux de Neurons)

* **Pour dataset "Data ESC-10" :**

In [8]:
import os
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

scaler = StandardScaler()
X_train_data_ESC10 = scaler.fit_transform(X_train_data_ESC10)
X_test_data_ESC10 = scaler.transform(X_test_data_ESC10)

# Spécifie le dossier pour les prévisions et le rapport de classification
output_folder_data_ESC10 = "Predictions et Rapport de Classification Data ESC-10"
os.makedirs(output_folder_data_ESC10, exist_ok=True)

# Spécifie les chemins complets pour les prévisions et le rapport de classification
predictions_path_data_ESC10 = os.path.join(output_folder_data_ESC10, "Predictions.txt")
if os.path.exists(predictions_path_data_ESC10):
    os.remove(predictions_path_data_ESC10)

classification_report_path_data_ESC10 = os.path.join(output_folder_data_ESC10, "Classification_report.txt")
if os.path.exists(classification_report_path_data_ESC10):
    os.remove(classification_report_path_data_ESC10)
    
Top_10_per = [9, 41, 72, 49, 60, 77, 199, 130, 134, 156]
for i in Top_10_per :
    RNN = MLPClassifier(
         hidden_layer_sizes=(300, 100, 200),
         activation="relu",
         solver="adam",
         batch_size="auto",
         learning_rate="constant",
         max_iter=300,
         random_state=i
    )

    # Etablissement de la phase d'apprentissage
    RNN.fit(X_train_data_ESC10, y_train_data_ESC10)

    # Test le modèle proposé sur les données test
    y_pred_data_ESC10 =RNN.predict(X_test_data_ESC10)

    # Évalue les performances du modèle
    accuracy_data_ESC10 = accuracy_score(y_test_data_ESC10, y_pred_data_ESC10) # Mésurer la précison(accuracy) de système sur l'ensemble des données test
    conf_matrix_data_ESC10 = confusion_matrix(y_test_data_ESC10, y_pred_data_ESC10) # Afficher la matrice de confusion qui montre la relation entre les données prédit par l'algorithme

    # Pour les données de test réel
    classification_rep_data_ESC10 = classification_report(y_test_data_ESC10, y_pred_data_ESC10)# un rapport globale de classification est fournit permttant ainsi d'analyser les résultats obtenus
    
    # Sauvegarder les prédictions dans un fichier appellé predictions.txt via la fonction with open
    with open(predictions_path_data_ESC10, "a") as pred_file:
        pred_file.write(f"Top_10_per = {i}\n")
        for pred in y_pred_data_ESC10:
            pred_file.write(f"{pred}\n")

    # Sauvegarde le rapport de classification dans un fichier
    with open(classification_report_path_data_ESC10, "a") as report_file:
        report_file.write(f"Top_10_per = {i}\n")
        report_file.write(classification_rep_data_ESC10)

    # Affiche le chemin des fichiers de sortie (TOP 10)
    print(f"Top_10_per = {i}\n")
    print(f"Predictions saved at: {predictions_path_data_ESC10}")
    print(f"Classification report saved at: {classification_report_path_data_ESC10}")


    # Affiche les résultats (TOP 10)
    print(f"Accuracy: {accuracy_data_ESC10}")
    print(f"Confusion Matrix:\n{conf_matrix_data_ESC10}")
    print(f"Classification Report:\n{classification_rep_data_ESC10}")

Top_10_per = 9

Predictions saved at: Predictions et Rapport de Classification Data ESC-10/Predictions.txt
Classification report saved at: Predictions et Rapport de Classification Data ESC-10/Classification_report.txt
Accuracy: 0.7875
Confusion Matrix:
[[4 0 0 0 0 3 1 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 2 6 0 0 0 0 0 0 0]
 [0 1 0 7 0 0 0 0 0 0]
 [0 0 0 0 7 1 0 0 0 0]
 [0 0 0 0 0 8 0 0 0 0]
 [0 0 0 0 0 0 7 1 0 0]
 [0 2 0 0 1 0 0 5 0 0]
 [1 0 0 0 0 0 0 0 7 0]
 [0 0 0 0 4 0 0 0 0 4]]
Classification Report:
                      precision    recall  f1-score   support

      001 - Dog bark       0.80      0.50      0.62         8
          002 - Rain       0.62      1.00      0.76         8
     003 - Sea waves       1.00      0.75      0.86         8
      004 - Baby cry       1.00      0.88      0.93         8
    005 - Clock tick       0.58      0.88      0.70         8
 006 - Person sneeze       0.67      1.00      0.80         8
    007 - Helicopter       0.88      0.88      0.88       

* **Pour dataset "Data" :**

In [9]:
import os
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

scaler = StandardScaler()
X_train_data = scaler.fit_transform(X_train_data)
X_test_data = scaler.transform(X_test_data)

# Spécifie le dossier pour les prévisions et le rapport de classification
output_folder_data = "Predictions et Rapport de Classification Data"
os.makedirs(output_folder_data, exist_ok=True)

# Spécifie les chemins complets pour les prévisions et le rapport de classification
predictions_path_data = os.path.join(output_folder_data, "Predictions.txt")
if os.path.exists(predictions_path_data):
    os.remove(predictions_path_data)

classification_report_path_data = os.path.join(output_folder_data, "Classification_report.txt")
if os.path.exists(classification_report_path_data):
    os.remove(classification_report_path_data)

Top_10_per = [61, 55, 27, 35, 11, 21, 18, 82, 2, 3]
for i in Top_10_per :
    RNN = MLPClassifier(
         hidden_layer_sizes=(300, 100, 200),
         activation="relu",
         solver="adam",
         batch_size="auto",
         learning_rate="constant",
         max_iter=300,
         random_state=i
    )

    # Etablissement de la phase d'apprentissage
    RNN.fit(X_train_data, y_train_data)

    # Test le modèle proposé sur les données test
    y_pred_data =RNN.predict(X_test_data)

    # Évalue les performances du modèle
    accuracy_data = accuracy_score(y_test_data, y_pred_data) # Mésurer la précison(accuracy) de système sur l'ensemble des données test
    conf_matrix_data = confusion_matrix(y_test_data, y_pred_data) # Afficher la matrice de confusion qui montre la relation entre les données prédit par l'algorithme

    # Pour les données de test réel
    classification_rep_data = classification_report(y_test_data, y_pred_data)# un rapport globale de classification est fournit permttant ainsi d'analyser les résultats obtenus
    
    # Sauvegarder les prédictions dans un fichier appellé predictions.txt via la fonction with open
    with open(predictions_path_data, "a") as pred_file:
        pred_file.write(f"Top_10_per = {i}\n")
        for pred in y_pred_data:
            pred_file.write(f"{pred}\n")

    # Sauvegarde le rapport de classification dans un fichier
    with open(classification_report_path_data, "a") as report_file:
        report_file.write(f"Top_10_per = {i}\n")
        report_file.write(classification_rep_data)

    # Affiche le chemin des fichiers de sortie (TOP 10)
    print(f"Top_10_per = {i}\n")
    print(f"Predictions saved at: {predictions_path_data}")
    print(f"Classification report saved at: {classification_report_path_data}")


    # Affiche les résultats (TOP 10)
    print(f"Accuracy: {accuracy_data}")
    print(f"Confusion Matrix:\n{conf_matrix_data}")
    print(f"Classification Report:\n{classification_rep_data}")

Top_10_per = 61

Predictions saved at: Predictions et Rapport de Classification Data/Predictions.txt
Classification report saved at: Predictions et Rapport de Classification Data/Classification_report.txt
Accuracy: 0.75
Confusion Matrix:
[[6 1 0 0 1]
 [2 6 0 0 0]
 [1 0 7 0 0]
 [3 0 0 5 0]
 [0 0 1 1 6]]
Classification Report:
               precision    recall  f1-score   support

    101 - Dog       0.50      0.75      0.60         8
102 - Rooster       0.86      0.75      0.80         8
    103 - Pig       0.88      0.88      0.88         8
    104 - Cow       0.83      0.62      0.71         8
   105 - Frog       0.86      0.75      0.80         8

     accuracy                           0.75        40
    macro avg       0.78      0.75      0.76        40
 weighted avg       0.78      0.75      0.76        40

Top_10_per = 55

Predictions saved at: Predictions et Rapport de Classification Data/Predictions.txt
Classification report saved at: Predictions et Rapport de Classification D

# Avec KNeighbors Classifier (KNN)

* **Pour dataset "Data ESC-10" :**

In [10]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

KNN = KNeighborsClassifier()
KNN.fit(X_train_data_ESC10, y_train_data_ESC10)
KNN_pred = KNN.predict(X_test_data_ESC10)

# Évalue les performances du modèle
accuracy_knn_data_ESC10 = accuracy_score(y_test_data_ESC10, KNN_pred)
conf_matrix_knn_data_ESC10 = confusion_matrix(y_test_data_ESC10, KNN_pred)
classification_rep_knn_data_ESC10 = classification_report(y_test_data_ESC10, KNN_pred)

# Affiche les résultats
print(f"Accuracy: {accuracy_knn_data_ESC10}")
print(f"Confusion Matrix:\n{conf_matrix_knn_data_ESC10}")
print(f"Classification Report:\n{classification_rep_knn_data_ESC10}")

Accuracy: 0.4875
Confusion Matrix:
[[2 0 0 0 1 4 0 0 0 1]
 [0 6 2 0 0 0 0 0 0 0]
 [0 1 7 0 0 0 0 0 0 0]
 [1 0 2 3 0 2 0 0 0 0]
 [1 0 1 0 4 0 0 0 0 2]
 [0 1 0 0 0 7 0 0 0 0]
 [0 2 3 0 0 0 3 0 0 0]
 [0 4 2 0 0 0 1 1 0 0]
 [0 0 0 1 1 5 0 0 1 0]
 [0 0 0 0 1 2 0 0 0 5]]
Classification Report:
                      precision    recall  f1-score   support

      001 - Dog bark       0.50      0.25      0.33         8
          002 - Rain       0.43      0.75      0.55         8
     003 - Sea waves       0.41      0.88      0.56         8
      004 - Baby cry       0.75      0.38      0.50         8
    005 - Clock tick       0.57      0.50      0.53         8
 006 - Person sneeze       0.35      0.88      0.50         8
    007 - Helicopter       0.75      0.38      0.50         8
      008 - Chainsaw       1.00      0.12      0.22         8
       009 - Rooster       1.00      0.12      0.22         8
010 - Fire crackling       0.62      0.62      0.62         8

            accuracy       

* **Pour dataset "Data" :**

In [11]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

KNN = KNeighborsClassifier()
KNN.fit(X_train_data, y_train_data)
KNN_pred = KNN.predict(X_test_data)

# Évalue les performances du modèle
accuracy_knn_data = accuracy_score(y_test_data, KNN_pred)
conf_matrix_knn_data = confusion_matrix(y_test_data, KNN_pred)
classification_rep_knn_data = classification_report(y_test_data, KNN_pred)

# Affiche les résultats
print(f"Accuracy: {accuracy_knn_data}")
print(f"Confusion Matrix:\n{conf_matrix_knn_data}")
print(f"Classification Report:\n{classification_rep_knn_data}")

Accuracy: 0.575
Confusion Matrix:
[[7 0 1 0 0]
 [2 6 0 0 0]
 [2 0 6 0 0]
 [3 0 4 0 1]
 [1 1 1 1 4]]
Classification Report:
               precision    recall  f1-score   support

    101 - Dog       0.47      0.88      0.61         8
102 - Rooster       0.86      0.75      0.80         8
    103 - Pig       0.50      0.75      0.60         8
    104 - Cow       0.00      0.00      0.00         8
   105 - Frog       0.80      0.50      0.62         8

     accuracy                           0.57        40
    macro avg       0.52      0.57      0.52        40
 weighted avg       0.52      0.57      0.52        40



# Avec Les Arbres de decision (Decision Tree Classifier)

* **Pour dataset "Data ESC-10" :**

In [12]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

DTC = DecisionTreeClassifier()
DTC.fit(X_train_data_ESC10, y_train_data_ESC10)
DTC_pred = DTC.predict(X_test_data_ESC10)

# Évalue les performances du modèle
accuracy_dtc_data_ESC10 = accuracy_score(y_test_data_ESC10, DTC_pred)
conf_matrix_dtc_data_ESC10 = confusion_matrix(y_test_data_ESC10, DTC_pred)
classification_rep_dtc_data_ESC10 = classification_report(y_test_data_ESC10, DTC_pred)

# Affiche les résultats
print(f"Accuracy: {accuracy_dtc_data_ESC10}")
print(f"Confusion Matrix:\n{conf_matrix_dtc_data_ESC10}")
print(f"Classification Report:\n{classification_rep_dtc_data_ESC10}")

Accuracy: 0.625
Confusion Matrix:
[[5 1 0 0 0 0 0 0 2 0]
 [0 6 1 1 0 0 0 0 0 0]
 [0 0 4 0 0 0 2 2 0 0]
 [2 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 7 0 0 0 0 1]
 [2 0 0 0 0 6 0 0 0 0]
 [0 2 0 0 0 0 5 1 0 0]
 [0 4 0 2 0 0 0 2 0 0]
 [2 0 0 0 0 0 0 0 6 0]
 [1 1 0 0 2 1 0 0 0 3]]
Classification Report:
                      precision    recall  f1-score   support

      001 - Dog bark       0.42      0.62      0.50         8
          002 - Rain       0.43      0.75      0.55         8
     003 - Sea waves       0.80      0.50      0.62         8
      004 - Baby cry       0.67      0.75      0.71         8
    005 - Clock tick       0.78      0.88      0.82         8
 006 - Person sneeze       0.86      0.75      0.80         8
    007 - Helicopter       0.71      0.62      0.67         8
      008 - Chainsaw       0.40      0.25      0.31         8
       009 - Rooster       0.75      0.75      0.75         8
010 - Fire crackling       0.75      0.38      0.50         8

            accuracy        

* **Pour dataset "Data" :**

In [13]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

DTC = DecisionTreeClassifier()
DTC.fit(X_train_data, y_train_data)
DTC_pred = DTC.predict(X_test_data)

# Évalue les performances du modèle
accuracy_dtc_data = accuracy_score(y_test_data, DTC_pred)
conf_matrix_dtc_data = confusion_matrix(y_test_data, DTC_pred)
classification_rep_dtc_data = classification_report(y_test_data, DTC_pred)

# Affiche les résultats
print(f"Accuracy: {accuracy_dtc_data}")
print(f"Confusion Matrix:\n{conf_matrix_dtc_data}")
print(f"Classification Report:\n{classification_rep_dtc_data}")

Accuracy: 0.675
Confusion Matrix:
[[4 2 2 0 0]
 [1 7 0 0 0]
 [1 1 6 0 0]
 [0 1 2 5 0]
 [2 0 1 0 5]]
Classification Report:
               precision    recall  f1-score   support

    101 - Dog       0.50      0.50      0.50         8
102 - Rooster       0.64      0.88      0.74         8
    103 - Pig       0.55      0.75      0.63         8
    104 - Cow       1.00      0.62      0.77         8
   105 - Frog       1.00      0.62      0.77         8

     accuracy                           0.68        40
    macro avg       0.74      0.68      0.68        40
 weighted avg       0.74      0.68      0.68        40



# Avec Random Forest Classifier

* **Pour dataset "Data ESC-10" :**

In [14]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

RFC = RandomForestClassifier()
RFC.fit(X_train_data_ESC10, y_train_data_ESC10)
RFC_pred = RFC.predict(X_test_data_ESC10)

# Évalue les performances du modèle
accuracy_rfc_data_ESC10 = accuracy_score(y_test_data_ESC10, RFC_pred)
conf_matrix_rfc_data_ESC10 = confusion_matrix(y_test_data_ESC10, RFC_pred)
classification_rep_rfc_data_ESC10 = classification_report(y_test_data_ESC10, RFC_pred)

# Affiche les résultats
print(f"Accuracy: {accuracy_rfc_data_ESC10}")
print(f"Confusion Matrix:\n{conf_matrix_rfc_data_ESC10}")
print(f"Classification Report:\n{classification_rep_rfc_data_ESC10}")

Accuracy: 0.8625
Confusion Matrix:
[[5 0 0 0 0 0 1 0 2 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 1 7 0 0 0 0 0 0 0]
 [0 0 0 7 0 1 0 0 0 0]
 [0 0 0 0 7 0 1 0 0 0]
 [0 0 0 0 0 8 0 0 0 0]
 [0 0 0 0 0 0 7 1 0 0]
 [1 1 0 0 0 0 0 6 0 0]
 [0 0 0 0 0 0 0 0 8 0]
 [0 0 0 0 2 0 0 0 0 6]]
Classification Report:
                      precision    recall  f1-score   support

      001 - Dog bark       0.83      0.62      0.71         8
          002 - Rain       0.80      1.00      0.89         8
     003 - Sea waves       1.00      0.88      0.93         8
      004 - Baby cry       1.00      0.88      0.93         8
    005 - Clock tick       0.78      0.88      0.82         8
 006 - Person sneeze       0.89      1.00      0.94         8
    007 - Helicopter       0.78      0.88      0.82         8
      008 - Chainsaw       0.86      0.75      0.80         8
       009 - Rooster       0.80      1.00      0.89         8
010 - Fire crackling       1.00      0.75      0.86         8

            accuracy       

* **Pour dataset "Data" :**

In [15]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

RFC = RandomForestClassifier()
RFC.fit(X_train_data, y_train_data)
RFC_pred = RFC.predict(X_test_data)

# Évalue les performances du modèle
accuracy_rfc_data = accuracy_score(y_test_data, RFC_pred)
conf_matrix_rfc_data = confusion_matrix(y_test_data, RFC_pred)
classification_rep_rfc_data = classification_report(y_test_data, RFC_pred)

# Affiche les résultats
print(f"Accuracy: {accuracy_rfc_data}")
print(f"Confusion Matrix:\n{conf_matrix_rfc_data}")
print(f"Classification Report:\n{classification_rep_rfc_data}")

Accuracy: 0.9
Confusion Matrix:
[[5 2 0 1 0]
 [0 8 0 0 0]
 [0 0 7 0 1]
 [0 0 0 8 0]
 [0 0 0 0 8]]
Classification Report:
               precision    recall  f1-score   support

    101 - Dog       1.00      0.62      0.77         8
102 - Rooster       0.80      1.00      0.89         8
    103 - Pig       1.00      0.88      0.93         8
    104 - Cow       0.89      1.00      0.94         8
   105 - Frog       0.89      1.00      0.94         8

     accuracy                           0.90        40
    macro avg       0.92      0.90      0.89        40
 weighted avg       0.92      0.90      0.89        40



# Avec SVM (SVC)

* **Pour dataset "Data ESC-10" :**

In [16]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

SVM = SVC()
SVM.fit(X_train_data_ESC10, y_train_data_ESC10)
SVM_pred = SVM.predict(X_test_data_ESC10)

# Évalue les performances du modèle
accuracy_svm_data_ESC10 = accuracy_score(y_test_data_ESC10, SVM_pred)
conf_matrix_svm_data_ESC10 = confusion_matrix(y_test_data_ESC10, SVM_pred)
classification_rep_svm_data_ESC10 = classification_report(y_test_data_ESC10, SVM_pred)

# Affiche les résultats
print(f"Accuracy: {accuracy_svm_data_ESC10}")
print(f"Confusion Matrix:\n{conf_matrix_svm_data_ESC10}")
print(f"Classification Report:\n{classification_rep_svm_data_ESC10}")

Accuracy: 0.6625
Confusion Matrix:
[[2 0 0 0 2 4 0 0 0 0]
 [0 7 0 0 0 0 0 1 0 0]
 [0 1 6 0 0 0 0 0 0 1]
 [1 1 0 5 0 0 0 1 0 0]
 [0 0 0 1 5 0 0 0 0 2]
 [0 0 0 0 1 6 0 1 0 0]
 [0 0 0 0 0 0 7 1 0 0]
 [0 2 0 0 1 0 0 5 0 0]
 [1 0 0 0 0 1 0 2 4 0]
 [0 0 0 0 2 0 0 0 0 6]]
Classification Report:
                      precision    recall  f1-score   support

      001 - Dog bark       0.50      0.25      0.33         8
          002 - Rain       0.64      0.88      0.74         8
     003 - Sea waves       1.00      0.75      0.86         8
      004 - Baby cry       0.83      0.62      0.71         8
    005 - Clock tick       0.45      0.62      0.53         8
 006 - Person sneeze       0.55      0.75      0.63         8
    007 - Helicopter       1.00      0.88      0.93         8
      008 - Chainsaw       0.45      0.62      0.53         8
       009 - Rooster       1.00      0.50      0.67         8
010 - Fire crackling       0.67      0.75      0.71         8

            accuracy       

* **Pour dataset "Data" :**

In [17]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

SVM = SVC()
SVM.fit(X_train_data, y_train_data)
SVM_pred = SVM.predict(X_test_data)

# Évalue les performances du modèle
accuracy_svm_data = accuracy_score(y_test_data, SVM_pred)
conf_matrix_svm_data = confusion_matrix(y_test_data, SVM_pred)
classification_rep_svm_data = classification_report(y_test_data, SVM_pred)

# Affiche les résultats
print(f"Accuracy: {accuracy_svm_data}")
print(f"Confusion Matrix:\n{conf_matrix_svm_data}")
print(f"Classification Report:\n{classification_rep_svm_data}")

Accuracy: 0.575
Confusion Matrix:
[[2 4 1 0 1]
 [2 4 1 1 0]
 [1 1 5 0 1]
 [1 0 1 6 0]
 [0 0 1 1 6]]
Classification Report:
               precision    recall  f1-score   support

    101 - Dog       0.33      0.25      0.29         8
102 - Rooster       0.44      0.50      0.47         8
    103 - Pig       0.56      0.62      0.59         8
    104 - Cow       0.75      0.75      0.75         8
   105 - Frog       0.75      0.75      0.75         8

     accuracy                           0.57        40
    macro avg       0.57      0.57      0.57        40
 weighted avg       0.57      0.57      0.57        40

